//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kingmaker
{
    using System;
    using System.Collections.Generic;
    
    public partial class masscombat_commander
    {
        public int i_id { get; set; }
        public string vc_commander { get; set; }
        public int i_charisma { get; set; }
        public int i_mental_ability { get; set; }
        public int i_profession_soldier { get; set; }
        public int i_bonus_melee { get; set; }
        public int i_bonus_ranged { get; set; }
        public int i_bonus_defensive { get; set; }
        public int i_bonus_health { get; set; }
        public int i_bonus_morale { get; set; }
        public int i_bonus_fortitude { get; set; }
        public int i_bonus_reflex { get; set; }
        public int i_bonus_upkeep { get; set; }
        public bool b_council_position { get; set; }
        public int i_leadership_role_id { get; set; }
        public int i_hit_dice { get; set; }
        public bool b_feat_leadership { get; set; }
        public int i_bonus_leadership { get; set; }
        public Nullable<int> i_faction_id { get; set; }
        public string t_token { get; set; }
    }
}
