//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kingmaker
{
    using System;
    using System.Collections.Generic;
    
    public partial class masscombat_equipment_armor_movement
    {
        public int i_id { get; set; }
        public int i_base { get; set; }
        public int i_medium { get; set; }
        public int i_heavy { get; set; }
    }
}
