//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kingmaker
{
    using System;
    using System.Collections.Generic;
    
    public partial class masscombat_unit
    {
        public int i_id { get; set; }
        public string vc_unit { get; set; }
        public int i_size_id { get; set; }
        public int i_type_id { get; set; }
        public int i_level_id { get; set; }
        public int i_xp { get; set; }
        public int i_specialization_id { get; set; }
        public int i_race_id { get; set; }
        public int i_faction_id { get; set; }
        public int i_commander_id { get; set; }
        public string t_icon { get; set; }
        public int i_mount_id { get; set; }
    }
}
