//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kingmaker
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MasscombatContext : DbContext
    {
        public MasscombatContext()
            : base("name=MasscombatContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<masscombat_abilities_to_race> masscombat_abilities_to_race { get; set; }
        public virtual DbSet<masscombat_abilities_to_unit> masscombat_abilities_to_unit { get; set; }
        public virtual DbSet<masscombat_ability> masscombat_ability { get; set; }
        public virtual DbSet<masscombat_command> masscombat_command { get; set; }
        public virtual DbSet<masscombat_commander> masscombat_commander { get; set; }
        public virtual DbSet<masscombat_commands_to_commander> masscombat_commands_to_commander { get; set; }
        public virtual DbSet<masscombat_equipment> masscombat_equipment { get; set; }
        public virtual DbSet<masscombat_equipment_armor_movement> masscombat_equipment_armor_movement { get; set; }
        public virtual DbSet<masscombat_equipment_costs> masscombat_equipment_costs { get; set; }
        public virtual DbSet<masscombat_equipment_to_unit> masscombat_equipment_to_unit { get; set; }
        public virtual DbSet<masscombat_leadership_role_command> masscombat_leadership_role_command { get; set; }
        public virtual DbSet<masscombat_level> masscombat_level { get; set; }
        public virtual DbSet<masscombat_promotion> masscombat_promotion { get; set; }
        public virtual DbSet<masscombat_promotions_to_race> masscombat_promotions_to_race { get; set; }
        public virtual DbSet<masscombat_promotions_to_unit> masscombat_promotions_to_unit { get; set; }
        public virtual DbSet<masscombat_race> masscombat_race { get; set; }
        public virtual DbSet<masscombat_size> masscombat_size { get; set; }
        public virtual DbSet<masscombat_specialization> masscombat_specialization { get; set; }
        public virtual DbSet<masscombat_tactic> masscombat_tactic { get; set; }
        public virtual DbSet<masscombat_tactics_to_race> masscombat_tactics_to_race { get; set; }
        public virtual DbSet<masscombat_tactics_to_unit> masscombat_tactics_to_unit { get; set; }
        public virtual DbSet<masscombat_type> masscombat_type { get; set; }
        public virtual DbSet<masscombat_unit> masscombat_unit { get; set; }
        public virtual DbSet<masscombat_faction> masscombat_faction { get; set; }
    }
}
