//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kingmaker
{
    using System;
    using System.Collections.Generic;
    
    public partial class masscombat_ability
    {
        public int i_id { get; set; }
        public string vc_ability { get; set; }
        public int i_melee { get; set; }
        public int i_ranged { get; set; }
        public int i_defensive { get; set; }
        public float fl_health { get; set; }
        public float fl_movement_strategically { get; set; }
        public int i_movement_tactical { get; set; }
        public int i_morale { get; set; }
        public int i_fortitude { get; set; }
        public int i_reflex { get; set; }
        public float fl_value { get; set; }
        public float fl_upkeep { get; set; }
        public string vc_tooltip { get; set; }
        public string vc_description { get; set; }
    }
}
