//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kingmaker
{
    using System;
    using System.Collections.Generic;
    
    public partial class masscombat_abilities_to_unit
    {
        public int i_id { get; set; }
        public int i_ability_id { get; set; }
        public int i_unit_id { get; set; }
    }
}
